from __future__ import annotations

import json
import math
import shutil
from datetime import datetime
from pathlib import Path

import yaml

from simcoach.adapters.ams2 import AMS2Adapter
from simcoach.adapters.base import NormalizedTick
from simcoach.analysis.run import analyze_session
from simcoach.ingest.session import (
    atomic_write_jsonl,
    atomic_write_text,
    atomic_write_yaml,
    derive_lap_records,
    paths_for,
    write_ticks_parquet,
)
from tests.test_adapters import CREST_FIXTURE, make_crest_snapshot
from tests.test_session import session_info

REPO_ROOT = Path(__file__).resolve().parents[1]
ANALYSIS_OUTPUT_ROOT = REPO_ROOT / "data" / "test_outputs" / "inspectable_analysis"
SESSION_DIR = ANALYSIS_OUTPUT_ROOT / "recorded_session"
ACTUAL_SNAPSHOT_OUTPUT_ROOT = REPO_ROOT / "data" / "test_outputs" / "actual_pcars2_snapshot"


def test_analysis_run_produces_inspectable_outputs() -> None:
    """Generate a real Recorded Session and Analysis Run under data/test_outputs."""

    if ANALYSIS_OUTPUT_ROOT.exists():
        shutil.rmtree(ANALYSIS_OUTPUT_ROOT)
    SESSION_DIR.mkdir(parents=True)

    info = session_info()
    session_id = "inspectable-actual-session"
    started_at = datetime.fromisoformat("2026-06-12T10:00:00-07:00")
    paths = paths_for(SESSION_DIR)
    ticks = build_reportable_concrete_fixture_ticks()
    frame = write_ticks_parquet(paths.ticks_parquet, ticks)
    laps = derive_lap_records(frame, session_id)

    atomic_write_jsonl(paths.laps_jsonl, laps)
    atomic_write_yaml(
        paths.session_yaml,
        {
            "session_schema_version": info["session_schema_version"],
            "tick_schema_version": info["tick_schema_version"],
            "lap_schema_version": info["lap_schema_version"],
            "recorded_session_id": session_id,
            "sim": info["sim"],
            "track_raw": info["track_raw"],
            "track": info["track"],
            "car_raw": info["car_raw"],
            "car": info["car"],
            "session_type": info["session_type"],
            "started_at": started_at.isoformat(),
            "ended_at": "2026-06-12T10:10:00-07:00",
            "tick_rate_hz": 60,
            "track_length_m": info["track_length_m"],
            "lap_dist_m_source": info["lap_dist_m_source"],
            "adapter_version": info["adapter_version"],
            "validity_method": info["validity_method"],
            "complete": True,
            "failure_reason": None,
            "notes": "Inspectable pytest fixture using concrete normalized tick data.",
        },
    )

    run_dir = analyze_session(SESSION_DIR)

    expected_artifacts = {
        "session_yaml": paths.session_yaml,
        "ticks_parquet": paths.ticks_parquet,
        "laps_jsonl": paths.laps_jsonl,
        "session_coach_report": paths.coach_report,
        "analysis_yaml": run_dir / "analysis.yaml",
        "selected_delta": run_dir / "selected_delta.json",
        "corner_segments": run_dir / "corner_segments.json",
        "run_coach_report": run_dir / "coach_report.md",
    }
    for artifact in expected_artifacts.values():
        assert artifact.exists(), artifact

    analysis_yaml = yaml.safe_load(expected_artifacts["analysis_yaml"].read_text())
    selected_delta = json.loads(expected_artifacts["selected_delta"].read_text())
    coach_report = expected_artifacts["run_coach_report"].read_text()

    assert analysis_yaml["run_status"] == "complete"
    assert analysis_yaml["analysis_status"] == "reportable"
    assert selected_delta["analysis_status"] == "reportable"
    assert selected_delta["selected_delta"]["dominant_cause"] == "min_speed"
    assert "carry more minimum speed" in coach_report

    atomic_write_text(
        ANALYSIS_OUTPUT_ROOT / "output_index.json",
        json.dumps(
            {
                "description": "Inspectable outputs generated by pytest.",
                "regenerate_with": (
                    "uv run pytest tests/test_inspectable_analysis_output.py -q"
                ),
                "recorded_session_path": str(SESSION_DIR),
                "analysis_run_path": str(run_dir),
                "artifacts": {
                    name: str(path) for name, path in sorted(expected_artifacts.items())
                },
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
    )


def test_actual_pcars2_fixture_produces_inspectable_adapter_outputs() -> None:
    """Convert a committed Project CARS 2 sample into normalized SIM-COACH outputs."""

    if ACTUAL_SNAPSHOT_OUTPUT_ROOT.exists():
        shutil.rmtree(ACTUAL_SNAPSHOT_OUTPUT_ROOT)
    ACTUAL_SNAPSHOT_OUTPUT_ROOT.mkdir(parents=True)

    sample = json.loads(CREST_FIXTURE.read_text(encoding="utf-8-sig"))
    snapshot = make_crest_snapshot(sample)
    session_info_from_sample = AMS2Adapter.session_info_from_snapshot(snapshot)
    tick = AMS2Adapter.tick_from_snapshot(snapshot, capture_t=0.0)

    assert session_info_from_sample is not None
    assert tick is not None
    assert session_info_from_sample["track_raw"] == "Azure Circuit Grand Prix"
    assert session_info_from_sample["car_raw"] == "Renault Megane R.S. 265"
    assert math.isclose(tick.lap_dist_m or 0.0, 400.639, rel_tol=0.0, abs_tol=0.001)
    assert tick.speed > 0.0

    artifact_paths = {
        "source_fixture": CREST_FIXTURE,
        "session_info": ACTUAL_SNAPSHOT_OUTPUT_ROOT / "session_info.yaml",
        "normalized_tick": ACTUAL_SNAPSHOT_OUTPUT_ROOT / "normalized_tick.json",
    }
    atomic_write_yaml(artifact_paths["session_info"], dict(session_info_from_sample))
    atomic_write_text(
        artifact_paths["normalized_tick"],
        json.dumps(tick.as_record(), indent=2, sort_keys=True) + "\n",
    )
    atomic_write_text(
        ACTUAL_SNAPSHOT_OUTPUT_ROOT / "output_index.json",
        json.dumps(
            {
                "description": "Outputs from the committed Project CARS 2 CREST sample.",
                "source_fixture": str(CREST_FIXTURE),
                "regenerate_with": (
                    "uv run pytest tests/test_inspectable_analysis_output.py -q"
                ),
                "artifacts": {
                    name: str(path) for name, path in sorted(artifact_paths.items())
                },
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
    )

    for name, artifact in artifact_paths.items():
        if name != "source_fixture":
            assert artifact.exists(), artifact


def build_reportable_concrete_fixture_ticks() -> list[NormalizedTick]:
    ticks: list[NormalizedTick] = []
    rows_per_lap = 240
    base_t = 0.0
    for lap in range(1, 7):
        is_reference = lap == 1
        lap_duration = 90.0 if is_reference else 90.18
        for index in range(rows_per_lap):
            pct = index / rows_per_lap
            in_loss_region = 0.18 <= pct <= 0.42
            corner_delay = 0.0 if is_reference else 0.18 * smoothstep(0.18, 0.42, pct)
            elapsed = pct * lap_duration + corner_delay
            angle = 2.0 * math.pi * pct
            speed = 45.0
            if in_loss_region:
                speed = 42.0 if is_reference else 39.0
            ticks.append(
                NormalizedTick(
                    t=base_t + elapsed,
                    lap=lap,
                    lap_dist_pct=pct,
                    lap_dist_m=pct * 4309.0,
                    speed=speed,
                    throttle=0.7,
                    brake=0.0,
                    steering=0.2,
                    gear=4,
                    rpm=8500.0,
                    vehicle_state="running",
                    pos_x=100.0 * math.cos(angle),
                    pos_y=100.0 * math.sin(angle),
                    pos_z=0.0,
                )
            )
        base_t += lap_duration + 1.0
    return ticks


def smoothstep(start: float, end: float, value: float) -> float:
    if value <= start:
        return 0.0
    if value >= end:
        return 1.0
    x = (value - start) / (end - start)
    return x * x * (3.0 - 2.0 * x)
